=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 3 (http://www.altova.com) by NTT (norg) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="Excel" targetNamespace="Excel" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="PurchaseOrder">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Items">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="itemCount" type="xs:int"/>
							<xs:element name="Item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="yourPartnerNumber" type="xs:string"/>
										<xs:element name="unitPrice" type="xs:decimal"/>
										<xs:element name="unitOfMeasure" type="xs:string"/>
										<xs:element name="salesValue" type="xs:decimal"/>
										<xs:element name="quantity" type="xs:decimal"/>
										<xs:element name="partNumber" type="xs:string"/>
										<xs:element name="partDescription" type="xs:string"/>
										<xs:element name="itemNumber" type="xs:int"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DeliverTo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Contact" type="ns:Contact"/>
							<xs:element name="Address" type="ns:Address"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="InvoiceTo">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Contact" type="ns:Contact"/>
							<xs:element name="Address" type="ns:Address"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Header">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="orderNum" type="xs:string"/>
							<xs:element name="orderDate" type="xs:date"/>
							<xs:element name="ourAccountCode" type="xs:string"/>
							<xs:element name="yourAccountCode" type="xs:string"/>
							<xs:element name="Contact" type="ns:Contact"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Footer">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="totalValue" type="xs:decimal"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Address">
		<xs:sequence>
			<xs:element name="street1" type="xs:string"/>
			<xs:element name="street2" type="xs:string"/>
			<xs:element name="street3" type="xs:string"/>
			<xs:element name="street4" type="xs:string"/>
			<xs:element name="stateProvince" type="xs:string"/>
			<xs:element name="postalCode" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Contact">
		<xs:sequence>
			<xs:element name="contactName" type="xs:string"/>
			<xs:element name="companyName" type="xs:string"/>
			<xs:element name="e-mail" type="xs:string"/>
			<xs:element name="telephone" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_6.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>1223</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>d38292</ns:yourPartnerNumber>
      <ns:unitPrice>15.3</ns:unitPrice>
      <ns:unitOfMeasure>kg</ns:unitOfMeasure>
      <ns:salesValue>30.4</ns:salesValue>
      <ns:quantity>2</ns:quantity>
      <ns:partNumber>s667</ns:partNumber>
      <ns:partDescription>potatos</ns:partDescription>
      <ns:itemNumber>243</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Dr. Gilboa Barak</ns:contactName>
      <ns:companyName>Shuk ha karmel</ns:companyName>
      <ns:e-mail>shuk@gmail.com</ns:e-mail>
      <ns:telephone>03-2193822</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>karmel 67</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>26534</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Tel Aviv</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Dr. Gilboa Barak</ns:contactName>
      <ns:companyName>Shuk ha karmel</ns:companyName>
      <ns:e-mail>shuk@gmail.com</ns:e-mail>
      <ns:telephone>03-9823373</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>karmel 67</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>56887</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Tel Aviv</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>PO937506</ns:orderNum>
    <ns:orderDate>2013-12-23</ns:orderDate>
    <ns:ourAccountCode>s6780</ns:ourAccountCode>
    <ns:yourAccountCode>a5678</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Dr. Gilboa Barak</ns:contactName>
      <ns:companyName>Shuk ha karmel</ns:companyName>
      <ns:e-mail>shuk@gmail.com</ns:e-mail>
      <ns:telephone>03-9823373</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>40.2</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>19</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>787i74</ns:yourPartnerNumber>
      <ns:unitPrice>1258</ns:unitPrice>
      <ns:unitOfMeasure>kg</ns:unitOfMeasure>
      <ns:salesValue>1259854.58</ns:salesValue>
      <ns:quantity>58</ns:quantity>
      <ns:partNumber>t459</ns:partNumber>
      <ns:partDescription>Porsche early 944 924s relay/fuse box from a 1985 944</ns:partDescription>
      <ns:itemNumber>857599</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Chandler Bing</ns:contactName>
      <ns:companyName>Cortica Ltd.</ns:companyName>
      <ns:e-mail>sales@cortica.com</ns:e-mail>
      <ns:telephone>(860) 832-2236</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Chestnut Street</ns:street1>
      <ns:street2>Eighth Avenue</ns:street2>
      <ns:street3>Pennsylvania Plaza</ns:street3>
      <ns:street4>96th Street</ns:street4>
      <ns:stateProvince>Arizona</ns:stateProvince>
      <ns:postalCode>58997</ns:postalCode>
      <ns:country>US</ns:country>
      <ns:city>Lake Havasu City</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Peter Dinklage</ns:contactName>
      <ns:companyName>Microsoft</ns:companyName>
      <ns:e-mail>pet.dinklage@microsoft.com</ns:e-mail>
      <ns:telephone>(877) 647-0788</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Plaza Way</ns:street1>
      <ns:street2>Orange Campus</ns:street2>
      <ns:street3>Building 5</ns:street3>
      <ns:street4>Suite #3246</ns:street4>
      <ns:stateProvince>Arizona</ns:stateProvince>
      <ns:postalCode>86442</ns:postalCode>
      <ns:country>US</ns:country>
      <ns:city>Bullhead City</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>4587525</ns:orderNum>
    <ns:orderDate>2011-09-11</ns:orderDate>
    <ns:ourAccountCode>U34A39</ns:ourAccountCode>
    <ns:yourAccountCode>U87A58</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Peter Dinklage</ns:contactName>
      <ns:companyName>Microsoft</ns:companyName>
      <ns:e-mail>pet.dinklage@microsoft.com</ns:e-mail>
      <ns:telephone>(877) 647-0788</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>4785.36</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>34</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>r83984</ns:yourPartnerNumber>
      <ns:unitPrice>4500</ns:unitPrice>
      <ns:unitOfMeasure>unit</ns:unitOfMeasure>
      <ns:salesValue>4500</ns:salesValue>
      <ns:quantity>1</ns:quantity>
      <ns:partNumber>i934</ns:partNumber>
      <ns:partDescription>iphone 5</ns:partDescription>
      <ns:itemNumber>23</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Miss Zoohar Malka</ns:contactName>
      <ns:companyName>Tiny Love</ns:companyName>
      <ns:e-mail>tlv@gmail.com</ns:e-mail>
      <ns:telephone>04-2637783</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Bareket 7</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>27362</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Kiryat Yam</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Miss Zoohar Malka</ns:contactName>
      <ns:companyName>Tiny Love</ns:companyName>
      <ns:e-mail>tlv@gmail.com</ns:e-mail>
      <ns:telephone>04-2637783</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Bareket 7</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>27362</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Kiryat Yam</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>PO293483</ns:orderNum>
    <ns:orderDate>2020-07-24</ns:orderDate>
    <ns:ourAccountCode>d7836</ns:ourAccountCode>
    <ns:yourAccountCode>w9722</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Miss Zoohar Malka</ns:contactName>
      <ns:companyName>Tiny Love</ns:companyName>
      <ns:e-mail>tlv@gmail.com</ns:e-mail>
      <ns:telephone>03-9823373</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>5000</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>457</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>2577iuy</ns:yourPartnerNumber>
      <ns:unitPrice>4558.58577</ns:unitPrice>
      <ns:unitOfMeasure>L</ns:unitOfMeasure>
      <ns:salesValue>4581.458</ns:salesValue>
      <ns:quantity>10.0</ns:quantity>
      <ns:partNumber>p754</ns:partNumber>
      <ns:partDescription>Jet Performance 67030 V-Force Plus</ns:partDescription>
      <ns:itemNumber>48856</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Yulia Shkolnik</ns:contactName>
      <ns:companyName>Atmos Energy</ns:companyName>
      <ns:e-mail>shkolnik@mail.com</ns:e-mail>
      <ns:telephone>(623) 453-2670</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Christopher Street</ns:street1>
      <ns:street2>Forsyth Street</ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince>CONNECTICUT</ns:stateProvince>
      <ns:postalCode>13417</ns:postalCode>
      <ns:country>USA</ns:country>
      <ns:city>Hartford</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Yulia Shkolnik</ns:contactName>
      <ns:companyName>Atmos Energy</ns:companyName>
      <ns:e-mail>shkolnik@mail.com</ns:e-mail>
      <ns:telephone>(623) 453-2670</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Christopher Street</ns:street1>
      <ns:street2>Forsyth Street</ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince>CONNECTICUT</ns:stateProvince>
      <ns:postalCode>13417</ns:postalCode>
      <ns:country>USA</ns:country>
      <ns:city>Hartford</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>4587</ns:orderNum>
    <ns:orderDate>2005-07-01</ns:orderDate>
    <ns:ourAccountCode>K45L56</ns:ourAccountCode>
    <ns:yourAccountCode>K45L99</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Yulia Shkolnik</ns:contactName>
      <ns:companyName>Atmos Energy</ns:companyName>
      <ns:e-mail>amos@gmail.com</ns:e-mail>
      <ns:telephone>(520) 205-5008</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>4550.0</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>12</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>d63457</ns:yourPartnerNumber>
      <ns:unitPrice>1237.82</ns:unitPrice>
      <ns:unitOfMeasure>kg</ns:unitOfMeasure>
      <ns:salesValue>1237.82</ns:salesValue>
      <ns:quantity>21</ns:quantity>
      <ns:partNumber>o975</ns:partNumber>
      <ns:partDescription>tomatos</ns:partDescription>
      <ns:itemNumber>12</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Tzeala Azulay</ns:contactName>
      <ns:companyName>Tamam Taasiyit mazon</ns:companyName>
      <ns:e-mail>tmm@yandex.ru</ns:e-mail>
      <ns:telephone>03-1223383</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Ben Guriyon 5</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>26534</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Petah Tikva</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Ayala Hason</ns:contactName>
      <ns:companyName>Tamam Taasiyit mazon</ns:companyName>
      <ns:e-mail>ayala@tamam.il</ns:e-mail>
      <ns:telephone>03-9823373</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Ben Guriyon 5</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>56887</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Petah Tikva</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>PO122323</ns:orderNum>
    <ns:orderDate>2013-05-13</ns:orderDate>
    <ns:ourAccountCode>d7654</ns:ourAccountCode>
    <ns:yourAccountCode>f9872</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Ayala Hason</ns:contactName>
      <ns:companyName>Tamam Taasiyit mazon</ns:companyName>
      <ns:e-mail>tamam@resor.uk</ns:e-mail>
      <ns:telephone>03-9823373</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>1227.2</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>85</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>yyiuu8</ns:yourPartnerNumber>
      <ns:unitPrice>458.99</ns:unitPrice>
      <ns:unitOfMeasure>kg</ns:unitOfMeasure>
      <ns:salesValue>458772.74</ns:salesValue>
      <ns:quantity>45.66</ns:quantity>
      <ns:partNumber>y865</ns:partNumber>
      <ns:partDescription>Honda Stage 3 Performance Chip Fuel Engine Racing Speed MOD Plug n Play</ns:partDescription>
      <ns:itemNumber>458871</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Patrick Stump</ns:contactName>
      <ns:companyName>Allegheny Technologies</ns:companyName>
      <ns:e-mail>Stumppet@yahoo.com</ns:e-mail>
      <ns:telephone>(623) 643-0399</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Camino San Xavier</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince>AZ</ns:stateProvince>
      <ns:postalCode>85308 </ns:postalCode>
      <ns:country>USA</ns:country>
      <ns:city>Glendale</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Patrick Stump</ns:contactName>
      <ns:companyName>Allegheny Technologies</ns:companyName>
      <ns:e-mail>Stumppet@yahoo.com</ns:e-mail>
      <ns:telephone>(623) 643-0399</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Camino San Xavier</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince>AZ</ns:stateProvince>
      <ns:postalCode>85308 </ns:postalCode>
      <ns:country>USA</ns:country>
      <ns:city>Glendale</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>75925</ns:orderNum>
    <ns:orderDate>2012-05-18</ns:orderDate>
    <ns:ourAccountCode>U34A88</ns:ourAccountCode>
    <ns:yourAccountCode>U34A74</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Patrick Stump</ns:contactName>
      <ns:companyName>Allegheny Technologies</ns:companyName>
      <ns:e-mail>Stumppet@yahoo.com</ns:e-mail>
      <ns:telephone>(480) 503-7355</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>1570.05</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>

=== JZCS2018/Ontobuilder-Research-Environment/datasets/PurchaseOrder/Excel/Excel_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<ns:PurchaseOrder xmlns:ns="Excel" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Excel Excel.xsd ">
  <ns:Items>
    <ns:itemCount>15</ns:itemCount>
    <ns:Item>
      <ns:yourPartnerNumber>s7829</ns:yourPartnerNumber>
      <ns:unitPrice>1229000</ns:unitPrice>
      <ns:unitOfMeasure>unit</ns:unitOfMeasure>
      <ns:salesValue>1300000</ns:salesValue>
      <ns:quantity>2</ns:quantity>
      <ns:partNumber>w029</ns:partNumber>
      <ns:partDescription>BMW cars</ns:partDescription>
      <ns:itemNumber>5</ns:itemNumber>
    </ns:Item>
  </ns:Items>
  <ns:DeliverTo>
    <ns:Contact>
      <ns:contactName>Prof Ofer Shtrayhaman</ns:contactName>
      <ns:companyName>BMW import</ns:companyName>
      <ns:e-mail>Netanya@hotmail.com</ns:e-mail>
      <ns:telephone>04-2637783</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Hazorfim</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>28933</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Netanya</ns:city>
    </ns:Address>
  </ns:DeliverTo>
  <ns:InvoiceTo>
    <ns:Contact>
      <ns:contactName>Prof Ofer Shtrayhaman</ns:contactName>
      <ns:companyName>BMW import</ns:companyName>
      <ns:e-mail>bmw@hotmail.com</ns:e-mail>
      <ns:telephone>09-3847382</ns:telephone>
    </ns:Contact>
    <ns:Address>
      <ns:street1>Hazorfim</ns:street1>
      <ns:street2></ns:street2>
      <ns:street3></ns:street3>
      <ns:street4></ns:street4>
      <ns:stateProvince></ns:stateProvince>
      <ns:postalCode>28933</ns:postalCode>
      <ns:country>Israel</ns:country>
      <ns:city>Netanya</ns:city>
    </ns:Address>
  </ns:InvoiceTo>
  <ns:Header>
    <ns:orderNum>PO203943</ns:orderNum>
    <ns:orderDate>2013-12-08</ns:orderDate>
    <ns:ourAccountCode>s7890</ns:ourAccountCode>
    <ns:yourAccountCode>w8765</ns:yourAccountCode>
    <ns:Contact>
      <ns:contactName>Prof Ofer Shtrayhaman</ns:contactName>
      <ns:companyName>BMW import</ns:companyName>
      <ns:e-mail>Netanya@hotmail.com</ns:e-mail>
      <ns:telephone>09-3847382</ns:telephone>
    </ns:Contact>
  </ns:Header>
  <ns:Footer>
    <ns:totalValue>1300000</ns:totalValue>
  </ns:Footer>
</ns:PurchaseOrder>
